builds:
- env:
  - CGO_ENABLED=0
  goos:
  - linux
  - darwin
  - freebsd
  - windows
  goarch:
  - amd64
  - arm64
  ldflags:
  - "-s -w"
  - "-extldflags=-zrelro"
  - "-extldflags=-znow"
  - "-X github.com/nsmith5/rekor-sidekick/cli.tag={{.Version}}"
  - "-X github.com/nsmith5/rekor-sidekick/cli.commit={{.FullCommit}}"
  - "-X github.com/nsmith5/rekor-sidekick/cli.date={{.CommitDate}}"

nfpms:
- id: default
  package_name: rekor-sidekick
  vendor: Nathan Smith
  homepage: https://www.nfsmith.ca
  maintainer: Nathan Smith <rekor-sidekick@nfsmith.ca>
  description: Alerting and monitoring of the Rekor signature transparency log
  formats:
  - apk
  - deb
  - rpm
  contents:
  - src: etc/config.yaml
    dst: /etc/rekor-sidekick/config.yaml
    type: config|noreplace
  - dst: /etc/rekor-sidekick
    type: dir
    file_info:
      mode: 0755

archives:
- id: binary
  format: binary

gomod:
  proxy: true

checksum:
  name_template: 'checksums.txt'

source:
  enabled: true

sboms:
- id: binaries
  artifacts: binary
- id: packages
  artifacts: package

signs:
- cmd: cosign
  env:
  - COSIGN_EXPERIMENTAL=1
  certificate: '${artifact}.pem'
  signature: '${artifact}.sig'
  args:
    - sign-blob
    - '--output-certificate=${certificate}'
    - '--output-signature=${signature}'
    - '${artifact}'
  artifacts: binary
  output: true
