name: Lint build and test

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  lint-build-test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest
    - name: build
      run: go build
    - name: test
      run: go test -race -covermode=atomic -coverprofile=coverage.out -v ./...
    - name: upload coverage
      uses: codecov/codecov-action@f32b3a3741e1053eb607407145bc9619351dc93b # v2.1.0
      with:
        files: coverage.out
